<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1003dd70-3fe7-466e-8d9d-64b00dd2c72a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResumeMatch.Core\ResumeMatch.Core.csproj" />
    <ProjectReference Include="..\ResumeMatch.Infrastructure\ResumeMatch.Infrastructure.csproj" />
  </ItemGroup>

</Project>
